set(Plugin-Name "Accuracy Test")
set(Plugin-Version "0.1")
set(Plugin-Vendor "Lancet")
set(Plugin-ContactAddress "https://github.com/zhaomengxiao/LancetMITK-Adition")
set(Require-Plugin org.mitk.gui.qt.common)
