.TH "AbstractDirector::AbstractDirectorPrivateImp" 3 "Mon Nov 21 2022" "Version 1.0.0" "LancetSpatialFitting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AbstractDirector::AbstractDirectorPrivateImp
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "itk::SmartPointer< \fBAbstractPipelineBuilder\fP > \fBbuilder\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBlancetSpatialFittingAbstractDirector\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "itk::SmartPointer<\fBAbstractPipelineBuilder\fP> AbstractDirector::AbstractDirectorPrivateImp::builder"

.PP
Definition at line \fB8\fP of file \fBlancetSpatialFittingAbstractDirector\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LancetSpatialFitting from the source code\&.
