.TH "src/lancetSpatialFittingAbstractDirector.h" 3 "Mon Nov 21 2022" "Version 1.0.0" "LancetSpatialFitting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/lancetSpatialFittingAbstractDirector.h
.SH SYNOPSIS
.br
.PP
\fC#include 'lancetSpatialFittingGlobal\&.h'\fP
.br
\fC#include <itkObject\&.h>\fP
.br
\fC#include <mitkCommon\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAbstractDirector\fP"
.br
.RI "This is the decision-maker class of the abstract generator pattern\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LancetSpatialFitting from the source code\&.
