.TH "src/core/lancetSpatialFittingNavigationToolCollector.cpp" 3 "Tue Nov 22 2022" "Version 1.0.0" "LancetSpatialFitting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/core/lancetSpatialFittingNavigationToolCollector.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'lancetSpatialFittingNavigationToolCollector\&.h'\fP
.br
\fC#include <QTimer>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBNavigationToolCollector::NavigationToolCollectorPrivateImp\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LancetSpatialFitting from the source code\&.
