.TH "src/lancetSpatialFittingGlobal.h" 3 "Mon Nov 21 2022" "Version 1.0.0" "LancetSpatialFitting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/lancetSpatialFittingGlobal.h
.SH SYNOPSIS
.br
.PP
\fC#include <org_mitk_lancet_services_spatialfitting_Export\&.h>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <itkObject\&.h>\fP
.br
\fC#include <itkSmartPointer\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLancetSpatialFittingNameSpace\fP"
.br
.RI "Global macro definition header file\&. "
.ti -1c
.RI "#define \fBCXX_NAMESPACE\fP   namespace"
.br
.ti -1c
.RI "#define \fBNAMESPACE_START_SCOPE\fP   {"
.br
.ti -1c
.RI "#define \fBNAMESPACE_CLOSE_SCOPE\fP   }"
.br
.ti -1c
.RI "#define \fBNAMSPEACE_DEFINE\fP"
.br
.ti -1c
.RI "#define \fBBEGIN_NAMSPEACE_DEFINE\fP(name)   \fBCXX_NAMESPACE\fP name \fBNAMESPACE_START_SCOPE\fP"
.br
.ti -1c
.RI "#define \fBEND_NAMSPEACE_DEFINE\fP(name)   \fBNAMESPACE_CLOSE_SCOPE\fP"
.br
.ti -1c
.RI "#define \fBBEGIN_SPATIAL_FITTING_NAMESPACE\fP   \fBBEGIN_NAMSPEACE_DEFINE\fP(lancet::spatial_fitting)"
.br
.ti -1c
.RI "#define \fBEND_SPATIAL_FITTING_NAMESPACE\fP   \fBEND_NAMSPEACE_DEFINE\fP(lancet::spatial_fitting)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BEGIN_NAMSPEACE_DEFINE(name)   \fBCXX_NAMESPACE\fP name \fBNAMESPACE_START_SCOPE\fP"

.PP
Definition at line \fB34\fP of file \fBlancetSpatialFittingGlobal\&.h\fP\&.
.SS "#define BEGIN_SPATIAL_FITTING_NAMESPACE   \fBBEGIN_NAMSPEACE_DEFINE\fP(lancet::spatial_fitting)"

.PP
Definition at line \fB39\fP of file \fBlancetSpatialFittingGlobal\&.h\fP\&.
.SS "#define CXX_NAMESPACE   namespace"

.PP
Definition at line \fB23\fP of file \fBlancetSpatialFittingGlobal\&.h\fP\&.
.SS "#define END_NAMSPEACE_DEFINE(name)   \fBNAMESPACE_CLOSE_SCOPE\fP"

.PP
Definition at line \fB35\fP of file \fBlancetSpatialFittingGlobal\&.h\fP\&.
.SS "#define END_SPATIAL_FITTING_NAMESPACE   \fBEND_NAMSPEACE_DEFINE\fP(lancet::spatial_fitting)"

.PP
Definition at line \fB40\fP of file \fBlancetSpatialFittingGlobal\&.h\fP\&.
.SS "#define NAMESPACE_CLOSE_SCOPE   }"

.PP
Definition at line \fB29\fP of file \fBlancetSpatialFittingGlobal\&.h\fP\&.
.SS "#define NAMESPACE_START_SCOPE   {"

.PP
Definition at line \fB27\fP of file \fBlancetSpatialFittingGlobal\&.h\fP\&.
.SS "#define NAMSPEACE_DEFINE"

.PP
Definition at line \fB33\fP of file \fBlancetSpatialFittingGlobal\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LancetSpatialFitting from the source code\&.
