.TH "lancet" 3 "Mon Nov 21 2022" "Version 1.0.0" "LancetSpatialFitting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lancet
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBorg_mitk_lancet_services_SpatialFitting\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBorg_mitk_lancet_services_SpatialFitting\fP \fBPluginActivator\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBorg_mitk_lancet_services_SpatialFitting\fP \fBlancet::PluginActivator\fP"

.PP
Definition at line \fB42\fP of file \fBlancetPluginActivator\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LancetSpatialFitting from the source code\&.
