.TH "lancet::org_mitk_lancet_services_SpatialFitting::PrivateImp" 3 "Tue Nov 22 2022" "Version 1.0.0" "LancetSpatialFitting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lancet::org_mitk_lancet_services_SpatialFitting::PrivateImp
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static ctkPluginContext * \fBpluginContext\fP = nullptr"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB12\fP of file \fBlancetPluginActivator\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "ctkPluginContext * lancet::PluginActivator::PrivateImp::pluginContext = nullptr\fC [static]\fP"

.PP
Definition at line \fB14\fP of file \fBlancetPluginActivator\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LancetSpatialFitting from the source code\&.
