.TH "src/internal/lancetPluginActivator.cpp" 3 "Tue Nov 22 2022" "Version 1.0.0" "LancetSpatialFitting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/internal/lancetPluginActivator.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'lancetPluginActivator\&.h'\fP
.br
\fC#include <usModuleRegistry\&.h>\fP
.br
\fC#include <usModule\&.h>\fP
.br
\fC#include <usModuleContext\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBlancet::org_mitk_lancet_services_SpatialFitting::PrivateImp\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlancet\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LancetSpatialFitting from the source code\&.
