.TH "NavigationToolToNavigationToolFilter" 3 "Tue Nov 22 2022" "Version 1.0.0" "LancetSpatialFitting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NavigationToolToNavigationToolFilter \- This is the header file that declares the data processing filter from space to space coordinate system of space fitting\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lancetSpatialFittingNavigationToolToNavigationToolFilter\&.h>\fP
.PP
Inherits mitk::NavigationDataToNavigationDataFilter\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBNavigationToolToNavigationToolFilterPrivateImp\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmitkClassMacro\fP (\fBNavigationToolToNavigationToolFilter\fP, mitk::NavigationDataToNavigationDataFilter)"
.br
.ti -1c
.RI "\fBNavigationToolToNavigationToolFilter\fP ()"
.br
.ti -1c
.RI "virtual \fB~NavigationToolToNavigationToolFilter\fP ()"
.br
.ti -1c
.RI "virtual mitk::NavigationData::Pointer \fBGetUCSTool\fP () const"
.br
.RI "Get the tool data object from the input data to the target coordinate system\&. "
.ti -1c
.RI "virtual void \fBSetUCSTool\fP (mitk::NavigationData::Pointer tool)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBGenerateData\fP () override"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is the header file that declares the data processing filter from space to space coordinate system of space fitting\&. 


.PP
\fBCopyright (C)2022-2023 Hangzhou Lancet Robot Co\&., Ltd\&. All rights reserved\&.\fP
.RS 4

.RE
.PP
\fBVersion\fP
.RS 4
V1\&.0\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2022-11-18 10:16:37
.RE
.PP
\fBModify History\fP
.RS 4

.IP "1." 4
Sun initialization the version for 2022-11-18 10:16:37\&.
.PP
.RE
.PP
\fBAuthor\fP
.RS 4
Sun 
.RE
.PP
\fBDate\fP
.RS 4
2022-11-18 10:16:37 
.RE
.PP
\fBRemarks\fP
.RS 4
Non
.RE
.PP
This is a tool to tool spatial data conversion filter\&.
.PP
This filter will transfer the navigation tool input data to the UCS tool coordinate system\&.
.PP
\fBWarning\fP
.RS 4
The filter itself will not monitor the validity of any data\&. If correct output data is required, please ensure the validity of the input data\&.
.br
.RE
.PP
Please refer to \fCmitk::NavigationDataToNavigationDataFilter\fP for details\&.
.PP
\fBClass diagram:\fP
.br
 
.PP
\fBAuthor\fP
.RS 4
Sun 
.RE
.PP
\fBVersion\fP
.RS 4
V1\&.0\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2022-11-18 17:21:18 
.RE
.PP
\fBRemarks\fP
.RS 4
Non
.RE
.PP
Contact: sh4a01@163.com 
.PP
Definition at line \fB54\fP of file \fBlancetSpatialFittingNavigationToolToNavigationToolFilter\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NavigationToolToNavigationToolFilter::NavigationToolToNavigationToolFilter ()"

.PP
Definition at line \fB10\fP of file \fBlancetSpatialFittingNavigationToolToNavigationToolFilter\&.cpp\fP\&.
.PP
.nf
11     : imp(std::make_shared<NavigationToolToNavigationToolFilterPrivateImp>())
12 {
13     
14 }
.fi
.SS "NavigationToolToNavigationToolFilter::~NavigationToolToNavigationToolFilter ()\fC [virtual]\fP"

.PP
Definition at line \fB16\fP of file \fBlancetSpatialFittingNavigationToolToNavigationToolFilter\&.cpp\fP\&.
.PP
.nf
17 {
18 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "void NavigationToolToNavigationToolFilter::GenerateData ()\fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB31\fP of file \fBlancetSpatialFittingNavigationToolToNavigationToolFilter\&.cpp\fP\&.
.PP
.nf
32 {
33 
34 }
.fi
.SS "mitk::NavigationData::Pointer NavigationToolToNavigationToolFilter::GetUCSTool () const\fC [virtual]\fP"

.PP
Get the tool data object from the input data to the target coordinate system\&. UCS: User Coordinate system\&. 
.PP
Definition at line \fB21\fP of file \fBlancetSpatialFittingNavigationToolToNavigationToolFilter\&.cpp\fP\&.
.PP
.nf
22 {
23     return mitk::NavigationData::Pointer();
24 }
.fi
.SS "NavigationToolToNavigationToolFilter::mitkClassMacro (\fBNavigationToolToNavigationToolFilter\fP, mitk::NavigationDataToNavigationDataFilter)"

.SS "void NavigationToolToNavigationToolFilter::SetUCSTool (mitk::NavigationData::Pointer tool)\fC [virtual]\fP"

.PP
Definition at line \fB26\fP of file \fBlancetSpatialFittingNavigationToolToNavigationToolFilter\&.cpp\fP\&.
.PP
.nf
28 {
29 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for LancetSpatialFitting from the source code\&.
