.TH "NavigationToolCollector::NavigationToolCollectorPrivateImp" 3 "Tue Nov 22 2022" "Version 1.0.0" "LancetSpatialFitting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NavigationToolCollector::NavigationToolCollectorPrivateImp
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QTimer \fBqtClockTrigger\fP"
.br
.ti -1c
.RI "unsigned int \fBnumberForMean\fP = 10"
.br
.ti -1c
.RI "double \fBaccuracyRange\fP = 0\&.5"
.br
.ti -1c
.RI "\fBWorkStatus\fP \fBstate\fP = WorkStatus::Idle"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBlancetSpatialFittingNavigationToolCollector\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double NavigationToolCollector::NavigationToolCollectorPrivateImp::accuracyRange = 0\&.5"

.PP
Definition at line \fB13\fP of file \fBlancetSpatialFittingNavigationToolCollector\&.cpp\fP\&.
.SS "unsigned int NavigationToolCollector::NavigationToolCollectorPrivateImp::numberForMean = 10"

.PP
Definition at line \fB12\fP of file \fBlancetSpatialFittingNavigationToolCollector\&.cpp\fP\&.
.SS "QTimer NavigationToolCollector::NavigationToolCollectorPrivateImp::qtClockTrigger"

.PP
Definition at line \fB11\fP of file \fBlancetSpatialFittingNavigationToolCollector\&.cpp\fP\&.
.SS "\fBWorkStatus\fP NavigationToolCollector::NavigationToolCollectorPrivateImp::state = WorkStatus::Idle"

.PP
Definition at line \fB14\fP of file \fBlancetSpatialFittingNavigationToolCollector\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LancetSpatialFitting from the source code\&.
