.TH "NavigationToolToSpaceFilter::NavigationToolToSpaceFilterPrivateImp" 3 "Mon Nov 21 2022" "Version 1.0.0" "LancetSpatialFitting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NavigationToolToSpaceFilter::NavigationToolToSpaceFilterPrivateImp
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "vtkMatrix4x4 * \fBconvertMatrix4x4\fP = vtkMatrix4x4::New()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBlancetSpatialFittingNavigationToolToSpaceFilter\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "vtkMatrix4x4* NavigationToolToSpaceFilter::NavigationToolToSpaceFilterPrivateImp::convertMatrix4x4 = vtkMatrix4x4::New()"

.PP
Definition at line \fB6\fP of file \fBlancetSpatialFittingNavigationToolToSpaceFilter\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LancetSpatialFitting from the source code\&.
