.TH "NavigationToolToNavigationToolFilter::NavigationToolToNavigationToolFilterPrivateImp" 3 "Tue Nov 22 2022" "Version 1.0.0" "LancetSpatialFitting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NavigationToolToNavigationToolFilter::NavigationToolToNavigationToolFilterPrivateImp
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "mitk::NavigationData::Pointer \fBucsTool\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBlancetSpatialFittingNavigationToolToNavigationToolFilter\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "mitk::NavigationData::Pointer NavigationToolToNavigationToolFilter::NavigationToolToNavigationToolFilterPrivateImp::ucsTool"

.PP
Definition at line \fB7\fP of file \fBlancetSpatialFittingNavigationToolToNavigationToolFilter\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LancetSpatialFitting from the source code\&.
