.TH "org_mitk_lancet_services_spatialfitting" 3 "Mon Nov 21 2022" "Version 1.0.0" "LancetSpatialFitting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org_mitk_lancet_services_spatialfitting \- Org_mitk_lancet_services_spatialfitting
.PP
 \- Spatial fitting data processing module\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNavigationToolCollector\fP"
.br
.RI "This is the header file that declares the navigation data collection filter\&. "
.ti -1c
.RI "class \fBNavigationToolToNavigationToolFilter\fP"
.br
.RI "This is the header file that declares the data processing filter from space to space coordinate system of space fitting\&. "
.ti -1c
.RI "class \fBNavigationToolToSpaceFilter\fP"
.br
.RI "This is the header file that declares the data processing filter from the tool of space fitting to the tool coordinate system\&. "
.ti -1c
.RI "class \fBPipelineBuilder\fP"
.br
.RI "This is an abstract pipeline data producer class\&. "
.ti -1c
.RI "class \fBPipelineManager\fP"
.br
.RI "$Document description$ "
.ti -1c
.RI "class \fBPointAccuracyDate\fP"
.br
.RI "This is the declaration header file of space point calculation\&. "
.ti -1c
.RI "class \fBRoboticsRegisterDirector\fP"
.br
.RI "This is the header file of the decision-maker for the registration and construction of the robot arm\&. "
.ti -1c
.RI "class \fBAbstractPipelineBuilder\fP"
.br
.RI "$Document description$ "
.ti -1c
.RI "class \fBAbstractDirector\fP"
.br
.RI "This is the decision-maker class of the abstract generator pattern\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLancetSpatialFittingNameSpace\fP"
.br
.RI "Global macro definition header file\&. "
.in -1c
.SH "Detailed Description"
.PP 
Spatial fitting data processing module\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define LancetSpatialFittingNameSpace"

.PP
Global macro definition header file\&. 
.PP
\fBCopyright (C)2022-2023 Hangzhou Lancet Robot Co\&., Ltd\&. All rights reserved\&.\fP
.RS 4

.RE
.PP
\fBVersion\fP
.RS 4
V1\&.0\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2022-11-18 10:32:42
.RE
.PP
\fBModify History\fP
.RS 4

.IP "1." 4
Sun initialization the version for 2022-11-18 10:32:42\&.
.PP
.RE
.PP
\fBRemarks\fP
.RS 4
Non 
.RE
.PP

.PP
Definition at line \fB19\fP of file \fBlancetSpatialFittingGlobal\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LancetSpatialFitting from the source code\&.
