.TH "PipelineBuilder::PipelineBuilderPrivateImp" 3 "Tue Nov 22 2022" "Version 1.0.0" "LancetSpatialFitting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PipelineBuilder::PipelineBuilderPrivateImp
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "itk::SmartPointer< \fBPipelineManager\fP > \fBpipelineManager\fP = PipelineManager::New()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBlancetSpatialFittingPipelineBuilder\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "itk::SmartPointer<\fBPipelineManager\fP> PipelineBuilder::PipelineBuilderPrivateImp::pipelineManager = PipelineManager::New()"

.PP
Definition at line \fB9\fP of file \fBlancetSpatialFittingPipelineBuilder\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LancetSpatialFitting from the source code\&.
