.TH "PipelineManager::PipelineManagerPrivateImp" 3 "Mon Nov 21 2022" "Version 1.0.0" "LancetSpatialFitting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PipelineManager::PipelineManagerPrivateImp
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< mitk::NavigationDataToNavigationDataFilter::Pointer > \fBvecFilterManage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBlancetSpatialFittingPipelineManager\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<mitk::NavigationDataToNavigationDataFilter::Pointer> PipelineManager::PipelineManagerPrivateImp::vecFilterManage"

.PP
Definition at line \fB7\fP of file \fBlancetSpatialFittingPipelineManager\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LancetSpatialFitting from the source code\&.
