.TH "PointAccuracyDate::PointAccuracyDatePrivateImp" 3 "Tue Nov 22 2022" "Version 1.0.0" "LancetSpatialFitting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PointAccuracyDate::PointAccuracyDatePrivateImp
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "mitk::Point3D \fBsrcPoint\fP"
.br
.ti -1c
.RI "mitk::Point3D \fBtargetPoint\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBlancetSpatialFittingPointAccuracyDate\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "mitk::Point3D PointAccuracyDate::PointAccuracyDatePrivateImp::srcPoint"

.PP
Definition at line \fB8\fP of file \fBlancetSpatialFittingPointAccuracyDate\&.cpp\fP\&.
.SS "mitk::Point3D PointAccuracyDate::PointAccuracyDatePrivateImp::targetPoint"

.PP
Definition at line \fB9\fP of file \fBlancetSpatialFittingPointAccuracyDate\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LancetSpatialFitting from the source code\&.
