.TH "RoboticsRegisterModel::RoboticsRegisterModelPrivateImp" 3 "Tue Nov 22 2022" "Version 1.0.0" "LancetSpatialFitting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RoboticsRegisterModel::RoboticsRegisterModelPrivateImp
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "RobotRegistration \fBroboticsRegisterModel\fP"
.br
.ti -1c
.RI "PipelineManager::Pointer \fBpipelineRoboticsRegisterManager\fP"
.br
.ti -1c
.RI "PipelineManager::Pointer \fBpipelineRoboticsAccuracyManager\fP"
.br
.ti -1c
.RI "mitk::NavigationDataSource * \fBndiNavigationDataSource\fP = nullptr"
.br
.ti -1c
.RI "mitk::NavigationDataSource * \fBroboticsNavigationDataSource\fP = nullptr"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBlancetSpatialFittingRoboticsRegisterModel\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "mitk::NavigationDataSource* RoboticsRegisterModel::RoboticsRegisterModelPrivateImp::ndiNavigationDataSource = nullptr"

.PP
Definition at line \fB14\fP of file \fBlancetSpatialFittingRoboticsRegisterModel\&.cpp\fP\&.
.SS "PipelineManager::Pointer RoboticsRegisterModel::RoboticsRegisterModelPrivateImp::pipelineRoboticsAccuracyManager"

.PP
Definition at line \fB12\fP of file \fBlancetSpatialFittingRoboticsRegisterModel\&.cpp\fP\&.
.SS "PipelineManager::Pointer RoboticsRegisterModel::RoboticsRegisterModelPrivateImp::pipelineRoboticsRegisterManager"

.PP
Definition at line \fB11\fP of file \fBlancetSpatialFittingRoboticsRegisterModel\&.cpp\fP\&.
.SS "mitk::NavigationDataSource* RoboticsRegisterModel::RoboticsRegisterModelPrivateImp::roboticsNavigationDataSource = nullptr"

.PP
Definition at line \fB15\fP of file \fBlancetSpatialFittingRoboticsRegisterModel\&.cpp\fP\&.
.SS "RobotRegistration RoboticsRegisterModel::RoboticsRegisterModelPrivateImp::roboticsRegisterModel"

.PP
Definition at line \fB9\fP of file \fBlancetSpatialFittingRoboticsRegisterModel\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LancetSpatialFitting from the source code\&.
