.TH "RoboticsRegisterModel" 3 "Tue Nov 22 2022" "Version 1.0.0" "LancetSpatialFitting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RoboticsRegisterModel
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lancetSpatialFittingRoboticsRegisterModel\&.h>\fP
.PP
Inherits itk::Object\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBRoboticsRegisterModelPrivateImp\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmitkClassMacroItkParent\fP (\fBRoboticsRegisterModel\fP, itk::Object) itkNewMacro(\fBRoboticsRegisterModel\fP) \fBRoboticsRegisterModel\fP()"
.br
.ti -1c
.RI "virtual \fB~RoboticsRegisterModel\fP ()"
.br
.ti -1c
.RI "RobotRegistration & \fBGetRegisterModel\fP ()"
.br
.ti -1c
.RI "itk::SmartPointer< \fBPipelineManager\fP > \fBGetRegisterNavigationPipeline\fP () const"
.br
.ti -1c
.RI "void \fBSetRegisterNavigationPipeline\fP (itk::SmartPointer< \fBPipelineManager\fP > manager)"
.br
.ti -1c
.RI "void \fBSetAccutacyVerifyPipeline\fP (itk::SmartPointer< \fBPipelineManager\fP > manager)"
.br
.ti -1c
.RI "itk::SmartPointer< \fBPipelineManager\fP > \fBGetAccutacyVerifyPipeline\fP () const"
.br
.ti -1c
.RI "mitk::NavigationDataSource * \fBGetNdiNavigationDataSource\fP () const"
.br
.ti -1c
.RI "void \fBSetNdiNavigationDataSource\fP (mitk::NavigationDataSource *source)"
.br
.ti -1c
.RI "mitk::NavigationDataSource * \fBGetRoboticsNavigationDataSource\fP () const"
.br
.ti -1c
.RI "void \fBSetRoboticsNavigationDataSource\fP (mitk::NavigationDataSource *source)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB27\fP of file \fBlancetSpatialFittingRoboticsRegisterModel\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RoboticsRegisterModel::~RoboticsRegisterModel ()\fC [virtual]\fP"

.PP
Definition at line \fB23\fP of file \fBlancetSpatialFittingRoboticsRegisterModel\&.cpp\fP\&.
.PP
.nf
24 {
25 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "itk::SmartPointer< \fBPipelineManager\fP > RoboticsRegisterModel::GetAccutacyVerifyPipeline () const"

.PP
Definition at line \fB45\fP of file \fBlancetSpatialFittingRoboticsRegisterModel\&.cpp\fP\&.
.PP
.nf
46 {
47     return itk::SmartPointer<PipelineManager>();
48 }
.fi
.SS "mitk::NavigationDataSource * RoboticsRegisterModel::GetNdiNavigationDataSource () const"

.PP
Definition at line \fB50\fP of file \fBlancetSpatialFittingRoboticsRegisterModel\&.cpp\fP\&.
.PP
.nf
51 {
52     return nullptr;
53 }
.fi
.SS "RobotRegistration & RoboticsRegisterModel::GetRegisterModel ()"

.PP
Definition at line \fB27\fP of file \fBlancetSpatialFittingRoboticsRegisterModel\&.cpp\fP\&.
.PP
.nf
28 {
29     return this->imp->roboticsRegisterModel;
30 }
.fi
.SS "itk::SmartPointer< \fBPipelineManager\fP > RoboticsRegisterModel::GetRegisterNavigationPipeline () const"

.PP
Definition at line \fB32\fP of file \fBlancetSpatialFittingRoboticsRegisterModel\&.cpp\fP\&.
.PP
.nf
33 {
34     return itk::SmartPointer<PipelineManager>();
35 }
.fi
.SS "mitk::NavigationDataSource * RoboticsRegisterModel::GetRoboticsNavigationDataSource () const"

.PP
Definition at line \fB59\fP of file \fBlancetSpatialFittingRoboticsRegisterModel\&.cpp\fP\&.
.PP
.nf
60 {
61     return nullptr;
62 }
.fi
.SS "RoboticsRegisterModel::mitkClassMacroItkParent (\fBRoboticsRegisterModel\fP, itk::Object)"

.SS "void RoboticsRegisterModel::SetAccutacyVerifyPipeline (itk::SmartPointer< \fBPipelineManager\fP > manager)"

.PP
Definition at line \fB41\fP of file \fBlancetSpatialFittingRoboticsRegisterModel\&.cpp\fP\&.
.PP
.nf
42 {
43 }
.fi
.SS "void RoboticsRegisterModel::SetNdiNavigationDataSource (mitk::NavigationDataSource * source)"

.PP
Definition at line \fB55\fP of file \fBlancetSpatialFittingRoboticsRegisterModel\&.cpp\fP\&.
.PP
.nf
56 {
57 }
.fi
.SS "void RoboticsRegisterModel::SetRegisterNavigationPipeline (itk::SmartPointer< \fBPipelineManager\fP > manager)"

.PP
Definition at line \fB37\fP of file \fBlancetSpatialFittingRoboticsRegisterModel\&.cpp\fP\&.
.PP
.nf
38 {
39 }
.fi
.SS "void RoboticsRegisterModel::SetRoboticsNavigationDataSource (mitk::NavigationDataSource * source)"

.PP
Definition at line \fB64\fP of file \fBlancetSpatialFittingRoboticsRegisterModel\&.cpp\fP\&.
.PP
.nf
65 {
66 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for LancetSpatialFitting from the source code\&.
