set(MITK_MODULES
  ExampleModule
  LancetAlgo
  LancetGeoUtil
  LancetRegistration
  LancetDRR
  LancetRobot
  LancetNCC
  LancetIGT
  LancetIGTUI
  LancetPrintDataHelper
  LancetFileIO
  LancetHardwareDevice
  #LancetSingleNodeWidgetInitor
  #LancetModelControl
  #LancetRobotRegistration
)
