set(MITK_PLUGINS
  org.mitk.lancet.statemachine.services:ON
  org.mitk.exampleplugin.eageractivation:ON
  org.mitk.gui.qt.exampleplugin:ON
  org.mitk.virtualcorrection:ON
  org.mitk.lancet.spinectregistration:ON
  org.mitk.lancet.movedata:ON
  org.mitk.lancet.spinecarmregistration:ON
  org.mitk.lancet.robot:ON
  org.mitk.lancet.accuracytest:ON
  org.mitk.lancet.dentalwidget:ON
  org.mitk.lancet.gui.qt.testsuite:ON
  org.mitk.lancet.view.deviceconfig:ON
  org.mitk.lancet.imageregistration:ON
  ##################   BEGIN(THA)    ####################
  org.mitk.lancet.medicalrecordmanagement:ON
  org.mitk.lancet.medicalrecordmanagement.editor:ON
  org.mitk.lancet.qctmark:ON
  org.mitk.lancet.disclaimeragreement:ON
  org.mitk.lancet.implantplanning:ON
  org.mitk.lancet.multirenderwidget.editor:ON
  org.mitk.lancet.linkinghardware:ON
  org.mitk.lancet.linkinghardware.editor:ON
  org.mitk.lancet.roboticsregistrations:ON
  org.mitk.lancet.roboticsregistrations.editor:ON
  org.mitk.lancet.roboticsregistrationsaccuracy:ON
  org.mitk.lancet.roboticsregistrationsaccuracy.editor:ON
  org.mitk.lancet.femurmarkerpoint:ON
  org.mitk.lancet.femurmarkerpoint.editor:ON
  org.mitk.lancet.femurroughregistrations:ON
  org.mitk.lancet.femurroughregistrations.editor:ON
  org.mitk.lancet.femurprecisionregistrations:ON
  org.mitk.lancet.femurprecisionregistrations.editor:ON
  org.mitk.lancet.pelvismarkerpoint:ON
  org.mitk.lancet.pelvismarkerpoint.editor:ON
  org.mitk.lancet.pelvisroughregistrations:ON
  org.mitk.lancet.pelvisroughregistrations.editor:ON
  org.mitk.lancet.pelvisprecisionregistrations:ON
  org.mitk.lancet.pelvisprecisionregistrations.editor:ON
  org.mitk.lancet.contusionaccuracy:ON
  org.mitk.lancet.contusionaccuracy.editor:ON
  org.mitk.lancet.contusion:ON
  org.mitk.lancet.contusion.editor:ON
  org.mitk.lancet.putmolarcupprosthesis:ON
  org.mitk.lancet.putmolarcupprosthesis.editor:ON
  org.mitk.lancet.putmolarcupprosthesisaccuracy:ON
  org.mitk.lancet.putmolarcupprosthesisaccuracy.editor:ON
  org.mitk.lancet.femurcontusion:ON
  org.mitk.lancet.femurcontusion.editor:ON
  org.mitk.lancet.putfemurprosthesisaccuracy:ON
  org.mitk.lancet.putfemurprosthesisaccuracy.editor:ON
  org.mitk.lancet.postoperativeoutcome:ON
  ##################    END(THA)   #######################
  org.mitk.lancet.htotest:ON
  org.mitk.lancet.surgicalsimulate:ON
  org.mitk.lancet.kukarobotcontrol:ON
  org.mitk.lancet.tha.application:ON
)
