set(MITK_PLUGINS
  org.mitk.exampleplugin.eageractivation:ON
  org.mitk.gui.qt.exampleplugin:ON
  org.mitk.virtualcorrection:OFF
  org.mitk.lancet.spinectregistration:ON
  org.mitk.lancet.movedata:ON
  org.mitk.lancet.spinecarmregistration:ON
  org.mitk.lancet.robot:ON
  org.mitk.lancet.accuracytest:ON
  org.mitk.lancet.dentalwidget:ON
  org.mitk.lancet.gui.qt.testsuite:ON
  org.mitk.lancet.view.deviceconfig:ON
  org.mitk.lancet.imageregistration:ON
  org.mitk.lancet.htotest:ON
  org.mitk.lancet.surgicalsimulate:ON
  org.mitk.lancet.kukarobotcontrol:ON
  org.mitk.lancet.hipplanning:ON
  org.mitk.lancet.cameratest:ON
  org.mitk.orthopedics.thaplan:ON
)
