/**
 * \par Copyright (C)2022-2023 Hangzhou Lancet Robot Co., Ltd. All rights reserved.
 *
 * \brief Builder abstract interface class
 * \ingroup org_mitk_lancet_services_spatialfitting
 * \version V1.0.0
 * \date 2022-11-18 10:14:00
 * 
 * \par Modify History
 *		-# Sun initialization the version for 2022-11-18 10:14:00.
 *
 * \author Sun
 * \remark Non
 */
#ifndef LancetSpatialFittingAbstractPipelineBuilder_H
#define LancetSpatialFittingAbstractPipelineBuilder_H

#include "lancetSpatialFittingGlobal.h"

// itk
#include <itkObject.h>

// mitk
#include <mitkCommon.h>

BEGIN_SPATIAL_FITTING_NAMESPACE
class PipelineManager;


/**
 * \ingroup org_mitk_lancet_services_spatialfitting
 * 
 * \brief Abstract interface class definition of Builder.
 *
 * This is the abstract class of pipeline data generator. Pipeline data is 
 * complex and changeable. The generator can effectively avoid the impact of 
 * changes in pipeline data on the basic code.
 *
 * <b>Class diagram:</b><br>
 * \image html SpatialFittingAbstractPipelineBuilder.svg
 * 
 * \author Sun
 * \date 2022-11-18 15:58:46
 * \remark Non
 *
 * Contact: sh4a01@163.com
 *
 */
class ORG_MITK_LANCET_SERVICES_SPATIALFITTING_PLUGIN 
	AbstractPipelineBuilder : public itk::Object
{
public:
	mitkClassMacroItkParent(AbstractPipelineBuilder, itk::Object);

	/**
	 * \brief Reset the internal resource or state of the generator to make it 
	 * appear as a clean existence.
	 *
	 * The derived class should override the interface to restore the internal 
	 * resources or state of the derived class to the initialized state.
	 *
	 */
	virtual void Reset() = 0;

	/**
	 * \brief Get the pipeline data object generated by the current constructor.
	 *
	 * Derived the production of pipeline data objects that should override the 
	 * interface function and implement generator operation.
	 *
	 * \return Pipe Data Manager objects.
	 */
	virtual itk::SmartPointer<PipelineManager> GetOutput() = 0;
};

END_SPATIAL_FITTING_NAMESPACE

#endif // !LancetSpatialFittingAbstractPipelineBuilder_H
