.TH "lancet::org_mitk_lancet_statemachine_services_Activator" 3 "Mon Sep 26 2022" "Version 1.0.0" "org.mitk.lancet.statemachine.services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lancet::org_mitk_lancet_statemachine_services_Activator
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lancetPluginActivator\&.h>\fP
.PP
Inherits QObject, and ctkPluginActivator\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBPrivateImp\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBorg_mitk_lancet_statemachine_services_Activator\fP ()"
.br
.ti -1c
.RI "virtual \fB~org_mitk_lancet_statemachine_services_Activator\fP () override"
.br
.ti -1c
.RI "void \fBstart\fP (ctkPluginContext *context) override"
.br
.ti -1c
.RI "void \fBstop\fP (ctkPluginContext *context) override"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static ctkPluginContext * \fBGetPluginContext\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const std::string \fBPLUGIN_ID\fP = 'org\&.mitk\&.lancet\&.statemachine\&.services'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB20\fP of file \fBlancetPluginActivator\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lancet::org_mitk_lancet_statemachine_services_Activator::org_mitk_lancet_statemachine_services_Activator ()"

.PP
Definition at line \fB21\fP of file \fBlancetPluginActivator\&.cpp\fP\&.
.SS "lancet::org_mitk_lancet_statemachine_services_Activator::~org_mitk_lancet_statemachine_services_Activator ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB27\fP of file \fBlancetPluginActivator\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "ctkPluginContext * lancet::org_mitk_lancet_statemachine_services_Activator::GetPluginContext ()\fC [static]\fP"

.PP
Definition at line \fB51\fP of file \fBlancetPluginActivator\&.cpp\fP\&.
.SS "void lancet::org_mitk_lancet_statemachine_services_Activator::start (ctkPluginContext * context)\fC [override]\fP"

.PP
Definition at line \fB31\fP of file \fBlancetPluginActivator\&.cpp\fP\&.
.SS "void lancet::org_mitk_lancet_statemachine_services_Activator::stop (ctkPluginContext * context)\fC [override]\fP"

.PP
Definition at line \fB45\fP of file \fBlancetPluginActivator\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const std::string lancet::org_mitk_lancet_statemachine_services_Activator::PLUGIN_ID = 'org\&.mitk\&.lancet\&.statemachine\&.services'\fC [static]\fP"

.PP
Definition at line \fB29\fP of file \fBlancetPluginActivator\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for org\&.mitk\&.lancet\&.statemachine\&.services from the source code\&.
