.TH "lancet::StateMachineActionProperty" 3 "Mon Sep 26 2022" "Version 1.0.0" "org.mitk.lancet.statemachine.services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lancet::StateMachineActionProperty \- Attributes of a private custom state machine element\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lancetStateMachineActionProperty\&.h>\fP
.PP
Inherits \fBlancet::IStateMachineActionProperty\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStateMachineActionProperty\fP ()"
.br
.ti -1c
.RI "\fBStateMachineActionProperty\fP (const QString &)"
.br
.ti -1c
.RI "\fBStateMachineActionProperty\fP (const berry::SmartPointer< \fBIScxmlStateMachineState\fP > &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Attributes of a private custom state machine element\&. 

This class is inherited from \fBlancet::IStateMachineActionProperty\fP\&. Please refer to superclass for details\&.
.PP
\fBAuthor\fP
.RS 4
Sun 
.RE
.PP
\fBVersion\fP
.RS 4
V1\&.0\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2022-09-26 17:31:18 
.RE
.PP
\fBRemarks\fP
.RS 4
Non
.RE
.PP
Contact: sh4a01@163.com 
.PP
Definition at line \fB28\fP of file \fBlancetStateMachineActionProperty\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lancet::StateMachineActionProperty::StateMachineActionProperty ()"

.PP
Definition at line \fB6\fP of file \fBlancetStateMachineActionProperty\&.cpp\fP\&.
.SS "lancet::StateMachineActionProperty::StateMachineActionProperty (const QString & id)"

.PP
Definition at line \fB12\fP of file \fBlancetStateMachineActionProperty\&.cpp\fP\&.
.SS "lancet::StateMachineActionProperty::StateMachineActionProperty (const berry::SmartPointer< \fBIScxmlStateMachineState\fP > & state)"

.PP
Definition at line \fB17\fP of file \fBlancetStateMachineActionProperty\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for org\&.mitk\&.lancet\&.statemachine\&.services from the source code\&.
