.TH "lancet::IStateMachineActionProperty::IStateMachineActionPropertyPrivateImp" 3 "Mon Sep 26 2022" "Version 1.0.0" "org.mitk.lancet.statemachine.services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lancet::IStateMachineActionProperty::IStateMachineActionPropertyPrivateImp
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBstateId\fP"
.br
.ti -1c
.RI "QString \fBstateUiName\fP"
.br
.ti -1c
.RI "QString \fBstateObjectName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBlancetIStateMachineActionProperty\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "QString lancet::IStateMachineActionProperty::IStateMachineActionPropertyPrivateImp::stateId"

.PP
Definition at line \fB8\fP of file \fBlancetIStateMachineActionProperty\&.cpp\fP\&.
.SS "QString lancet::IStateMachineActionProperty::IStateMachineActionPropertyPrivateImp::stateObjectName"

.PP
Definition at line \fB10\fP of file \fBlancetIStateMachineActionProperty\&.cpp\fP\&.
.SS "QString lancet::IStateMachineActionProperty::IStateMachineActionPropertyPrivateImp::stateUiName"

.PP
Definition at line \fB9\fP of file \fBlancetIStateMachineActionProperty\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for org\&.mitk\&.lancet\&.statemachine\&.services from the source code\&.
