.TH "lancet::IScxmlStateMachineService::IScxmlStateMachineServicePrivateImp" 3 "Mon Sep 26 2022" "Version 1.0.0" "org.mitk.lancet.statemachine.services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lancet::IScxmlStateMachineService::IScxmlStateMachineServicePrivateImp
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "IScxmlStateMachineState::Pointer \fBadminState\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static berry::SmartPointer< \fBIScxmlStateMachineService\fP > \fBstaticStateMachineService\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBlancetIScxmlStateMachineService\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "IScxmlStateMachineState::Pointer lancet::IScxmlStateMachineService::IScxmlStateMachineServicePrivateImp::adminState"

.PP
Definition at line \fB11\fP of file \fBlancetIScxmlStateMachineService\&.cpp\fP\&.
.SS "berry::SmartPointer< \fBIScxmlStateMachineService\fP > lancet::IScxmlStateMachineService::IScxmlStateMachineServicePrivateImp::staticStateMachineService\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=
        berry::SmartPointer<IScxmlStateMachineService>()
.fi
.PP
Definition at line \fB13\fP of file \fBlancetIScxmlStateMachineService\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for org\&.mitk\&.lancet\&.statemachine\&.services from the source code\&.
