.TH "lancet::IScxmlStateMachineState::IScxmlStateMachineStatePrivateImp" 3 "Mon Sep 26 2022" "Version 1.0.0" "org.mitk.lancet.statemachine.services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lancet::IScxmlStateMachineState::IScxmlStateMachineStatePrivateImp
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBactive\fP"
.br
.ti -1c
.RI "QString \fBstateId\fP"
.br
.ti -1c
.RI "\fBStateType\fP \fBstateType\fP"
.br
.ti -1c
.RI "QString \fBsubStateMachineScxmlAbsoluteFile\fP"
.br
.ti -1c
.RI "berry::SmartPointer< \fBIScxmStateMachineHandler\fP > \fBstateMachineHandler\fP"
.br
.ti -1c
.RI "berry::SmartPointer< \fBIScxmlStateMachineState\fP > \fBparentStateMachine\fP"
.br
.ti -1c
.RI "std::vector< berry::SmartPointer< \fBIScxmlStateMachineState\fP > > \fBsubStateMachines\fP"
.br
.ti -1c
.RI "QSharedPointer< QScxmlStateMachine > \fBqtStateMachine\fP"
.br
.ti -1c
.RI "berry::SmartPointer< \fBIStateMachineActionProperty\fP > \fBactionProperty\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBlancetIScxmlStateMachineState\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "berry::SmartPointer<\fBIStateMachineActionProperty\fP> lancet::IScxmlStateMachineState::IScxmlStateMachineStatePrivateImp::actionProperty"

.PP
Definition at line \fB24\fP of file \fBlancetIScxmlStateMachineState\&.cpp\fP\&.
.SS "bool lancet::IScxmlStateMachineState::IScxmlStateMachineStatePrivateImp::active"

.PP
Definition at line \fB13\fP of file \fBlancetIScxmlStateMachineState\&.cpp\fP\&.
.SS "berry::SmartPointer<\fBIScxmlStateMachineState\fP> lancet::IScxmlStateMachineState::IScxmlStateMachineStatePrivateImp::parentStateMachine"

.PP
Definition at line \fB19\fP of file \fBlancetIScxmlStateMachineState\&.cpp\fP\&.
.SS "QSharedPointer<QScxmlStateMachine> lancet::IScxmlStateMachineState::IScxmlStateMachineStatePrivateImp::qtStateMachine"

.PP
Definition at line \fB22\fP of file \fBlancetIScxmlStateMachineState\&.cpp\fP\&.
.SS "QString lancet::IScxmlStateMachineState::IScxmlStateMachineStatePrivateImp::stateId"

.PP
Definition at line \fB14\fP of file \fBlancetIScxmlStateMachineState\&.cpp\fP\&.
.SS "berry::SmartPointer<\fBIScxmStateMachineHandler\fP> lancet::IScxmlStateMachineState::IScxmlStateMachineStatePrivateImp::stateMachineHandler"

.PP
Definition at line \fB17\fP of file \fBlancetIScxmlStateMachineState\&.cpp\fP\&.
.SS "\fBStateType\fP lancet::IScxmlStateMachineState::IScxmlStateMachineStatePrivateImp::stateType"

.PP
Definition at line \fB15\fP of file \fBlancetIScxmlStateMachineState\&.cpp\fP\&.
.SS "std::vector<berry::SmartPointer<\fBIScxmlStateMachineState\fP> > lancet::IScxmlStateMachineState::IScxmlStateMachineStatePrivateImp::subStateMachines"

.PP
Definition at line \fB20\fP of file \fBlancetIScxmlStateMachineState\&.cpp\fP\&.
.SS "QString lancet::IScxmlStateMachineState::IScxmlStateMachineStatePrivateImp::subStateMachineScxmlAbsoluteFile"

.PP
Definition at line \fB16\fP of file \fBlancetIScxmlStateMachineState\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for org\&.mitk\&.lancet\&.statemachine\&.services from the source code\&.
