.TH "lancet::org_mitk_lancet_statemachine_services_Activator::PrivateImp" 3 "Mon Sep 26 2022" "Version 1.0.0" "org.mitk.lancet.statemachine.services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lancet::org_mitk_lancet_statemachine_services_Activator::PrivateImp
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ScxmlStateMachineService::Pointer \fBstateMachineService\fP = ScxmlStateMachineService::Pointer(nullptr)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static ctkPluginContext * \fBpluginContext\fP = nullptr"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBlancetPluginActivator\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "ctkPluginContext * lancet::org_mitk_lancet_statemachine_services_Activator::PrivateImp::pluginContext = nullptr\fC [static]\fP"

.PP
Definition at line \fB16\fP of file \fBlancetPluginActivator\&.cpp\fP\&.
.SS "ScxmlStateMachineService::Pointer lancet::org_mitk_lancet_statemachine_services_Activator::PrivateImp::stateMachineService = ScxmlStateMachineService::Pointer(nullptr)"

.PP
Definition at line \fB17\fP of file \fBlancetPluginActivator\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for org\&.mitk\&.lancet\&.statemachine\&.services from the source code\&.
