.TH "lancet::IScxmStateMachineHandler::IScxmStateMachineHandlerPrivateImp" 3 "Mon Sep 26 2022" "Version 1.0.0" "org.mitk.lancet.statemachine.services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lancet::IScxmStateMachineHandler::IScxmStateMachineHandlerPrivateImp
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "IScxmlStateMachineState::Pointer \fBstateAssignor\fP"
.br
.ti -1c
.RI "berry::SmartPointer< \fBIScxmlStateMachineState\fP > \fBstateActive\fP"
.br
.ti -1c
.RI "berry::SmartPointer< \fBIScxmlStateMachineState\fP > \fBlastStateActive\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB12\fP of file \fBlancetIScxmStateMachineHandler\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "berry::SmartPointer<\fBIScxmlStateMachineState\fP> lancet::IScxmStateMachineHandler::IScxmStateMachineHandlerPrivateImp::lastStateActive"

.PP
Definition at line \fB16\fP of file \fBlancetIScxmStateMachineHandler\&.cpp\fP\&.
.SS "berry::SmartPointer<\fBIScxmlStateMachineState\fP> lancet::IScxmStateMachineHandler::IScxmStateMachineHandlerPrivateImp::stateActive"

.PP
Definition at line \fB15\fP of file \fBlancetIScxmStateMachineHandler\&.cpp\fP\&.
.SS "IScxmlStateMachineState::Pointer lancet::IScxmStateMachineHandler::IScxmStateMachineHandlerPrivateImp::stateAssignor"

.PP
Definition at line \fB14\fP of file \fBlancetIScxmStateMachineHandler\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for org\&.mitk\&.lancet\&.statemachine\&.services from the source code\&.
