.TH "lancet::ScxmStateMachineHandler" 3 "Mon Sep 26 2022" "Version 1.0.0" "org.mitk.lancet.statemachine.services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lancet::ScxmStateMachineHandler \- Event processing unit of private state machine element\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lancetScxmStateMachineHandler\&.h>\fP
.PP
Inherits \fBlancet::IScxmStateMachineHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBberryObjectMacro\fP (\fBlancet::ScxmStateMachineHandler\fP)"
.br
.ti -1c
.RI "\fBScxmStateMachineHandler\fP ()"
.br
.ti -1c
.RI "\fBScxmStateMachineHandler\fP (berry::SmartPointer< \fBIScxmlStateMachineState\fP >)"
.br
.ti -1c
.RI "virtual \fB~ScxmStateMachineHandler\fP () override"
.br
.ti -1c
.RI "virtual bool \fBStartStateMachine\fP () override"
.br
.RI "Start or stop the state machine\&. "
.ti -1c
.RI "virtual bool \fBStopStateMachine\fP () override"
.br
.ti -1c
.RI "virtual bool \fBInit\fP (berry::SmartPointer< \fBIScxmlStateMachineState\fP >) override"
.br
.RI "Initialize the event processing class\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Event processing unit of private state machine element\&. 

This class is inherited from \fBlancet::IScxmStateMachineHandler\fP\&. Please refer to superclass for details\&.
.PP
\fBAuthor\fP
.RS 4
Sun 
.RE
.PP
\fBVersion\fP
.RS 4
V1\&.0\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2022-09-26 17:31:18 
.RE
.PP
\fBRemarks\fP
.RS 4
Non
.RE
.PP
Contact: sh4a01@163.com 
.PP
Definition at line \fB29\fP of file \fBlancetScxmStateMachineHandler\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lancet::ScxmStateMachineHandler::ScxmStateMachineHandler ()"

.PP
Definition at line \fB10\fP of file \fBlancetScxmStateMachineHandler\&.cpp\fP\&.
.SS "lancet::ScxmStateMachineHandler::ScxmStateMachineHandler (berry::SmartPointer< \fBIScxmlStateMachineState\fP > state)"

.PP
Definition at line \fB15\fP of file \fBlancetScxmStateMachineHandler\&.cpp\fP\&.
.SS "lancet::ScxmStateMachineHandler::~ScxmStateMachineHandler ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB20\fP of file \fBlancetScxmStateMachineHandler\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "lancet::ScxmStateMachineHandler::berryObjectMacro (\fBlancet::ScxmStateMachineHandler\fP)"

.SS "bool lancet::ScxmStateMachineHandler::Init (berry::SmartPointer< \fBIScxmlStateMachineState\fP > state)\fC [override]\fP, \fC [virtual]\fP"

.PP
Initialize the event processing class\&. This interface is a pure virtual property, and the inheritor needs to override this method to achieve initialization\&.
.PP
\fBWarning\fP
.RS 4
If the parameter input is empty, the event processing function is invalid\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fIstate\fP Monitoring state machine state objects\&.
.RE
.PP
\fBReturns\fP
.RS 4
Returns true if successful, otherwise false\&. 
.RE
.PP

.PP
Implements \fBlancet::IScxmStateMachineHandler\fP\&.
.PP
Definition at line \fB44\fP of file \fBlancetScxmStateMachineHandler\&.cpp\fP\&.
.SS "bool lancet::ScxmStateMachineHandler::StartStateMachine ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Start or stop the state machine\&. Starting the work of Qt state machine will not affect or operate the embedded sub state machine of Qt state machine\&.
.PP
Stopping the Qt state machine will stop all embedded sub Qt state machines\&.
.PP
\fBPrecondition\fP
.RS 4
This class must be initialized before executing this operation\&.
.RE
.PP
\fBReturns\fP
.RS 4
Returns true if successful, otherwise false\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBInit()\fP, \fBInitQtEventForStateMachine()\fP 
.RE
.PP

.PP
Implements \fBlancet::IScxmStateMachineHandler\fP\&.
.PP
Definition at line \fB24\fP of file \fBlancetScxmStateMachineHandler\&.cpp\fP\&.
.SS "bool lancet::ScxmStateMachineHandler::StopStateMachine ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBlancet::IScxmStateMachineHandler\fP\&.
.PP
Definition at line \fB34\fP of file \fBlancetScxmStateMachineHandler\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for org\&.mitk\&.lancet\&.statemachine\&.services from the source code\&.
