.TH "E:/LancetMITK-Adition/Plugins/org.mitk.lancet.statemachine.services/src/internal/lancetPluginActivator.h" 3 "Mon Sep 26 2022" "Version 1.0.0" "org.mitk.lancet.statemachine.services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/LancetMITK-Adition/Plugins/org.mitk.lancet.statemachine.services/src/internal/lancetPluginActivator.h
.SH SYNOPSIS
.br
.PP
\fC#include <ctkPluginActivator\&.h>\fP
.br
\fC#include <berrySmartPointer\&.h>\fP
.br
\fC#include <usServiceEvent\&.h>\fP
.br
\fC#include 'org_mitk_lancet_statemachine_services_Export\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlancet::org_mitk_lancet_statemachine_services_Activator\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBus\fP"
.br
.ti -1c
.RI "namespace \fBlancet\fP"
.br
.RI "Scope of Lancet Robot Co\&., Ltd\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef org_mitk_lancet_statemachine_services_Activator \fBlancet::PluginActivator\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for org\&.mitk\&.lancet\&.statemachine\&.services from the source code\&.
