.TH "lancet::plugin" 3 "Mon Sep 26 2022" "Version 1.0.0" "org.mitk.lancet.statemachine.services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lancet::plugin
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "QString LANCET_STATEMACHINE_SERVICES_PLUGIN \fBToMitkId\fP (const QString &qtStateId)"
.br
.RI "Change the state machine state ID to the plug-in ID in Mitk format\&. "
.ti -1c
.RI "QString LANCET_STATEMACHINE_SERVICES_PLUGIN \fBGetMitkPluginName\fP (const QString &)"
.br
.RI "Returns the name of a Mitk style plug-in\&. "
.ti -1c
.RI "QString LANCET_STATEMACHINE_SERVICES_PLUGIN \fBGetMitkPluginProductName\fP (const QString &)"
.br
.RI "Returns the product ID of the Mitk plug-in\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for org\&.mitk\&.lancet\&.statemachine\&.services from the source code\&.
