.TH "lancet::ScxmlStateMachineState" 3 "Mon Sep 26 2022" "Version 1.0.0" "org.mitk.lancet.statemachine.services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lancet::ScxmlStateMachineState \- Customized state machine elements\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lancetScxmStateMachineState\&.h>\fP
.PP
Inherits \fBlancet::IScxmlStateMachineState\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBberryObjectMacro\fP (\fBlancet::ScxmlStateMachineState\fP)"
.br
.ti -1c
.RI "\fBScxmlStateMachineState\fP (berry::SmartPointer< \fBIScxmlStateMachineState\fP > manage, \fBStateType\fP type, const QString &id)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Customized state machine elements\&. 

This class is inherited from \fBlancet::IScxmlStateMachineState\fP\&. Please refer to superclass for details\&.
.PP
\fBAuthor\fP
.RS 4
Sun 
.RE
.PP
\fBVersion\fP
.RS 4
V1\&.0\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2022-09-26 17:31:18 
.RE
.PP
\fBRemarks\fP
.RS 4
Non
.RE
.PP
Contact: sh4a01@163.com 
.PP
Definition at line \fB30\fP of file \fBlancetScxmStateMachineState\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lancet::ScxmlStateMachineState::ScxmlStateMachineState (berry::SmartPointer< \fBIScxmlStateMachineState\fP > manage, \fBIScxmlStateMachineState::StateType\fP type, const QString & id)"

.PP
Definition at line \fB6\fP of file \fBlancetScxmStateMachineState\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "lancet::ScxmlStateMachineState::berryObjectMacro (\fBlancet::ScxmlStateMachineState\fP)"


.SH "Author"
.PP 
Generated automatically by Doxygen for org\&.mitk\&.lancet\&.statemachine\&.services from the source code\&.
