.TH "E:/LancetMITK-Adition/Plugins/org.mitk.lancet.statemachine.services/src/internal/lancetNamingFormats.cpp" 3 "Mon Sep 26 2022" "Version 1.0.0" "org.mitk.lancet.statemachine.services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/LancetMITK-Adition/Plugins/org.mitk.lancet.statemachine.services/src/internal/lancetNamingFormats.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'lancetNamingFormats\&.h'\fP
.br
\fC#include <QDir>\fP
.br
\fC#include <QRegExp>\fP
.br
\fC#include <QStringList>\fP
.br
\fC#include 'lancetIScxmlStateMachineState\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlancet\fP"
.br
.RI "Scope of Lancet Robot Co\&., Ltd\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for org\&.mitk\&.lancet\&.statemachine\&.services from the source code\&.
