.TH "lancet" 3 "Mon Sep 26 2022" "Version 1.0.0" "org.mitk.lancet.statemachine.services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lancet \- Scope of Lancet Robot Co\&., Ltd\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBplugin\fP"
.br
.ti -1c
.RI "namespace \fBstate_machine\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIScxmlStateMachineLoader\fP"
.br
.RI "State Machine Loader, A complete state consists of attributes, SCXML, and events\&. "
.ti -1c
.RI "class \fBIScxmlStateMachineService\fP"
.br
.RI "This is the abstract class of state machine service\&. "
.ti -1c
.RI "class \fBIScxmlStateMachineState\fP"
.br
.RI "State description object of state machine\&. "
.ti -1c
.RI "class \fBIScxmStateMachineHandler\fP"
.br
.RI "This is the event processing abstract class of the state machine unit\&. "
.ti -1c
.RI "class \fBIStateMachineActionProperty\fP"
.br
.RI "Attribute abstract class of state machine element\&. "
.ti -1c
.RI "class \fBorg_mitk_lancet_statemachine_services_Activator\fP"
.br
.ti -1c
.RI "class \fBScxmlStateMachineLoader\fP"
.br
.RI "Loader for state machine service to load external files\&. "
.ti -1c
.RI "class \fBScxmlStateMachineService\fP"
.br
.RI "Private customized state machine service module entry\&. "
.ti -1c
.RI "class \fBScxmlStateMachineState\fP"
.br
.RI "Customized state machine elements\&. "
.ti -1c
.RI "class \fBScxmStateMachineHandler\fP"
.br
.RI "Event processing unit of private state machine element\&. "
.ti -1c
.RI "class \fBStateMachineActionProperty\fP"
.br
.RI "Attributes of a private custom state machine element\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBorg_mitk_lancet_statemachine_services_Activator\fP \fBPluginActivator\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Scope of Lancet Robot Co\&., Ltd\&. 

Declare a state machine service object\&.
.PP
State Machine Object Loader\&.
.PP
\fBCopyright (C)2022-2023 Hangzhou Lancet Robot Co\&., Ltd\&. All rights reserved\&.\fP
.RS 4

.RE
.PP
\fBVersion\fP
.RS 4
V1\&.0\&.0 \\data 2022-09-26 10:16:48
.RE
.PP
\fBModify History\fP
.RS 4

.RE
.PP
\fBAuthor\fP
.RS 4
Sun \\data 2022-09-26 10:16:48 
.RE
.PP
\fBRemarks\fP
.RS 4
Nothing
.RE
.PP
\fBCopyright (C)2022-2023 Hangzhou Lancet Robot Co\&., Ltd\&. All rights reserved\&.\fP
.RS 4

.RE
.PP
\fBVersion\fP
.RS 4
V1\&.0\&.0 \\data 2022-09-23 17:44:54
.RE
.PP
\fBModify History\fP
.RS 4

.RE
.PP
\fBAuthor\fP
.RS 4
Sun \\data 2022-09-23 17:44:54 
.RE
.PP
\fBRemarks\fP
.RS 4
Create initialize version\&. 
.RE
.PP

.SH "Typedef Documentation"
.PP 
.SS "typedef \fBorg_mitk_lancet_statemachine_services_Activator\fP \fBlancet::PluginActivator\fP"

.PP
Definition at line \fB43\fP of file \fBlancetPluginActivator\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for org\&.mitk\&.lancet\&.statemachine\&.services from the source code\&.
