.TH "lancet::state_machine" 3 "Mon Sep 26 2022" "Version 1.0.0" "org.mitk.lancet.statemachine.services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lancet::state_machine
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "QString LANCET_STATEMACHINE_SERVICES_PLUGIN \fBGetStateName\fP (const QString &)"
.br
.RI "Returns the state name of the state machine ID\&. "
.ti -1c
.RI "QString LANCET_STATEMACHINE_SERVICES_PLUGIN \fBGetModuleStateName\fP (const QString &)"
.br
.RI "Returns the state module name of the state machine ID\&. "
.ti -1c
.RI "QString LANCET_STATEMACHINE_SERVICES_PLUGIN \fBGetStateScxmlFileName\fP (const QString &, const QString &, int)"
.br
.RI "The path of the Qt state machine configuration file that returns the state machine ID\&. "
.ti -1c
.RI "QString LANCET_STATEMACHINE_SERVICES_PLUGIN \fBGetStateScxmlFolderName\fP (const QString &, const QString &, int)"
.br
.RI "The directory of the Qt state machine configuration file that returns the state machine ID\&. "
.ti -1c
.RI "QString LANCET_STATEMACHINE_SERVICES_PLUGIN \fBGetStatePropertyFileName\fP (const QString &, const QString &, int, const QString &='_subsidiary\&.json')"
.br
.RI "The absolute path of the Qt state machine property configuration file that returns the state machine ID\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for org\&.mitk\&.lancet\&.statemachine\&.services from the source code\&.
