.TH "lancet::IScxmlStateMachineLoader::IScxmlStateMachineLoaderPrivateImp" 3 "Mon Sep 26 2022" "Version 1.0.0" "org.mitk.lancet.statemachine.services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lancet::IScxmlStateMachineLoader::IScxmlStateMachineLoaderPrivateImp
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBisError\fP"
.br
.ti -1c
.RI "bool \fBisWarning\fP"
.br
.ti -1c
.RI "QString \fBfileName\fP"
.br
.ti -1c
.RI "QString \fBpropertyFileName\fP"
.br
.ti -1c
.RI "QString \fBsid\fP"
.br
.ti -1c
.RI "QStringList \fBlistErrorMessage\fP"
.br
.ti -1c
.RI "QStringList \fBlistWarningMessage\fP"
.br
.ti -1c
.RI "\fBIScxmlStateMachineState::StateType\fP \fBstateType\fP = IScxmlStateMachineState::StateType::Ordinary"
.br
.ti -1c
.RI "IScxmlStateMachineState::Pointer \fBmanageStateMachine\fP = IScxmlStateMachineState::Pointer(nullptr)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBlancetIScxmlStateMachineLoader\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "QString lancet::IScxmlStateMachineLoader::IScxmlStateMachineLoaderPrivateImp::fileName"

.PP
Definition at line \fB9\fP of file \fBlancetIScxmlStateMachineLoader\&.cpp\fP\&.
.SS "bool lancet::IScxmlStateMachineLoader::IScxmlStateMachineLoaderPrivateImp::isError"

.PP
Definition at line \fB7\fP of file \fBlancetIScxmlStateMachineLoader\&.cpp\fP\&.
.SS "bool lancet::IScxmlStateMachineLoader::IScxmlStateMachineLoaderPrivateImp::isWarning"

.PP
Definition at line \fB8\fP of file \fBlancetIScxmlStateMachineLoader\&.cpp\fP\&.
.SS "QStringList lancet::IScxmlStateMachineLoader::IScxmlStateMachineLoaderPrivateImp::listErrorMessage"

.PP
Definition at line \fB12\fP of file \fBlancetIScxmlStateMachineLoader\&.cpp\fP\&.
.SS "QStringList lancet::IScxmlStateMachineLoader::IScxmlStateMachineLoaderPrivateImp::listWarningMessage"

.PP
Definition at line \fB13\fP of file \fBlancetIScxmlStateMachineLoader\&.cpp\fP\&.
.SS "IScxmlStateMachineState::Pointer lancet::IScxmlStateMachineLoader::IScxmlStateMachineLoaderPrivateImp::manageStateMachine = IScxmlStateMachineState::Pointer(nullptr)"

.PP
Definition at line \fB15\fP of file \fBlancetIScxmlStateMachineLoader\&.cpp\fP\&.
.SS "QString lancet::IScxmlStateMachineLoader::IScxmlStateMachineLoaderPrivateImp::propertyFileName"

.PP
Definition at line \fB10\fP of file \fBlancetIScxmlStateMachineLoader\&.cpp\fP\&.
.SS "QString lancet::IScxmlStateMachineLoader::IScxmlStateMachineLoaderPrivateImp::sid"

.PP
Definition at line \fB11\fP of file \fBlancetIScxmlStateMachineLoader\&.cpp\fP\&.
.SS "\fBIScxmlStateMachineState::StateType\fP lancet::IScxmlStateMachineLoader::IScxmlStateMachineLoaderPrivateImp::stateType = IScxmlStateMachineState::StateType::Ordinary"

.PP
Definition at line \fB14\fP of file \fBlancetIScxmlStateMachineLoader\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for org\&.mitk\&.lancet\&.statemachine\&.services from the source code\&.
