.TH "todo" 3 "Mon Sep 26 2022" "Version 1.0.0" "org.mitk.lancet.statemachine.services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBMember \fBlancet::IScxmlStateMachineState::ToString\fP () const override\fP" 1c
To be realized \fBIScxmlStateMachineState::ToString(bool) const\fP 
.PP

