#ifndef COMMONUNIT_GLOBAL_H
#define COMMONUNIT_GLOBAL_H

#include <QtCore/qglobal.h>

/**
  * \brief Import/export macro definition
  */
#if defined(COMMONUNIT_LIBRARY)
    #define COMMONUNITSHARED_EXPORT Q_DECL_EXPORT
#else
    #define COMMONUNITSHARED_EXPORT Q_DECL_IMPORT
#endif

/**
  * \namespace lh_interface
  *
  * \brief lancet hardware interface, State some common resources
  */
namespace lh_interface
{

    /**
     * \brief Default no exception code value, all extension components should
     *        follow this standard.
     * */
    constexpr int default_normal = 0x00000000;

    /**
      * \enum   error_types
      * \brief  Enumerate the error levels as follows.
      */
    enum error_types
    {
        normal,     ///< Normal operation.
        debug,      ///< Information generated by the debugger.
        notice,     ///< It's not an error, but it may need to be handled.
        warning,    ///< Messages that require a business scope boundary or other circumstances.
        error,      ///< General error message.
        critical,   ///< Dangerous situations, such as hardware errors, may hinder some functions of the program.
        alert,      ///< Need immediate repair, such as hardware device offline.
        panic       ///< In case of emergency, if the system is unavailable (such as system crash), all users will be notified.
    };

    enum json_errors
    {
        NotError,               ///< Normal operation.
        NotFoundFile,           ///< File not found.
        NotValidJsonFile,       ///< Is not a valid JSON file.
        IODeviceInvalid,        ///< File read/write error.
        JsonFormatInvalid,      ///< Invalid file format.
        JsonObjectInvalid,      ///< The associated object is invalid.
        JsonFieldNotFound,      ///< No fields were found for the target JSON file.
    };
}
#endif // COMMONUNIT_GLOBAL_H
