
#ifndef THAFEMURSTEMCOUPLE_H
#define THAFEMURSTEMCOUPLE_H

#include <mitkImageToImageFilter.h>

// The following header file is generated by CMake and thus it's located in
// the build directory. It provides an export macro for classes and functions
// that you want to be part of the public interface of your module.
#include <MitkLancetIGTExports.h>

#include "lancetThaStemObject.h"
#include "lancetThaFemurObject.h"
#include "lancetThaPelvisCupCouple.h"
#include "mitkDataNode.h"
#include "mitkPointSet.h"
#include "mitkSurface.h"

namespace lancet
{
	/**Documentation
	  * \brief 
	  *
	  * \ingroup IGT
	  */
	class MITKLANCETIGT_EXPORT ThaFemurStemCouple : public itk::DataObject
	{
	public:
		mitkClassMacroItkParent(ThaFemurStemCouple, itk::DataObject);
		itkFactorylessNewMacro(Self)
		itkCloneMacro(Self)

		itkSetMacro(FemurObject, lancet::ThaFemurObject::Pointer)
		itkGetMacro(FemurObject, lancet::ThaFemurObject::Pointer)

		itkSetMacro(StemObject, lancet::ThaStemObject::Pointer)
		itkGetMacro(StemObject, lancet::ThaStemObject::Pointer)

		void SetCoupleGeometry(vtkSmartPointer<vtkMatrix4x4> newMatrix);
		itkGetMacro(vtkMatrix_coupleGeometry, vtkSmartPointer<vtkMatrix4x4>)

		void SetFemurFrameToStemFrameMatrix(vtkSmartPointer<vtkMatrix4x4> newMatrix);
		itkGetMacro(vtkMatrix_femurFrameToStemFrame, vtkSmartPointer<vtkMatrix4x4>)

		void InitializeFemurFrameToStemFrameMatrix();

		// Convenient method of getting the stem HeadCenter in femur frame
		mitk::Point3D GetStemHeadCenterInFemurFrame();

		// Calculate and return femurStemCoupleFrame --> femurCanalFrame
		vtkSmartPointer<vtkMatrix4x4> GetCoupleFrameToCanalFrame();

		vtkSmartPointer<vtkMatrix4x4> GetCoupleFrameToMechanicFrame();

		/* ToDo: Calculate and return the stem version:
		 * apply the same method of femoral version calculation
		 * but regard the stem pillar axis as new the neck axis*/
		double CalStemVersion();

		void ChangeHead(mitk::DataNode::Pointer headSurface,mitk::DataNode::Pointer headCenterPoint);

		void ChangeStem(mitk::DataNode::Pointer stemSurface,mitk::DataNode::Pointer cutplaneNormalPoint);

		//stem adjustment in different view
		void MoveStemUp(double step, ViewType view);

		void MoveStemDown(double step, ViewType view);

		void MoveStemLeft(double step, ViewType view);

		void MoveStemRight(double step, ViewType view);

		void RotateStemClockwise(double step, ViewType view);

		void RotateStemCounterClockwise(double step, ViewType view);

		void AppendExtrinsicMatrixToStemObject(vtkSmartPointer<vtkMatrix4x4> Matrix);

	protected:
		ThaFemurStemCouple();
		ThaFemurStemCouple(const ThaFemurStemCouple& other);
		~ThaFemurStemCouple() override;

		lancet::ThaFemurObject::Pointer m_FemurObject;

		lancet::ThaStemObject::Pointer m_StemObject;

		vtkSmartPointer<vtkMatrix4x4> m_vtkMatrix_femurFrameToStemFrame;

		vtkSmartPointer<vtkMatrix4x4> m_vtkMatrix_coupleGeometry;

		vtkSmartPointer<vtkMatrix4x4> m_vtkMatrix_coupleFrameToCanalFrame;

		vtkSmartPointer<vtkMatrix4x4> m_vtkMatrix_coupleFrameToMechanicFrame;

	};
}

#endif
