function(lancetFunctionFindVLD VLD_INSTALL_DIR)
  set(VLD_LIBRARY_LIST )
  foreach(libs_item $ENV{PATH})
    foreach(lib ${libs_item})
      string(FIND ${lib} "Visual Leak Detector" find_res REVERSE)
      if(NOT ${find_res} EQUAL -1)
		list(APPEND VLD_LIBRARY_LIST ${lib})
	  endif()
	endforeach()
  endforeach()
  
  foreach(lib_path ${VLD_LIBRARY_LIST})
    string(REPLACE "\\" "/" LIUNX_LIB_PATH ${lib_path})
    string(FIND ${LIUNX_LIB_PATH} "Visual Leak Detector/bin/Win64" find_vld_64 REVERSE)
	if(NOT ${find_vld_64} EQUAL -1)
	  string(REPLACE "/bin/Win64" "" LIUNX_VLD_INSTALL_DIR ${LIUNX_LIB_PATH})
	  set(VLD_INSTALL_DIR ${LIUNX_VLD_INSTALL_DIR} PARENT_SCOPE)
	  return()
	endif()
  endforeach()
endfunction()