NavigationToolCollector
WorkStatus
Unknown status.
ErrorCodes
The accuracy exceeds the acceptable range of the collector.
std::shared_ptr<NavigationToolCollectorPrivateImp> NavigationToolCollector::imp
NavigationToolCollector::mitkClassMacro(NavigationToolCollector, mitk::NavigationDataToNavigationDataFilter)
NavigationToolCollector::itkNewMacro(NavigationToolCollector) NavigationToolCollector()
NavigationToolCollector::~NavigationToolCollector()
References on_QtTimerTrigger_timeout.
long NavigationToolCollector::GetInterval() const
This property holds the timeout interval in milliseconds.
The default value for this property is 0. A QTimer with a timeout interval of 0 will time out as soon as all the events in the window system's event queue have been processed. Default initialization is 20 milliseconds. QTimer::setInterval, QTimer::interval
void NavigationToolCollector::SetInterval(long interval)
Referenced by Start.
unsigned int NavigationToolCollector::GetNumberForMean() const
Data Average Frames attribute.
This attribute determines the accuracy of the collector's output results. Theoretically, the larger the average frame number is, the more accurate the collector's output data will be without considering the performance. The working time of each collector is timer interval * average frames.
void NavigationToolCollector::SetNumberForMean(unsigned int number)
double NavigationToolCollector::GetAccuracyRange() const
Range property with acceptable precision.
When the absolute value of the fluctuation of the intermediate data to be collected is greater than the acceptable range, the collector will trigger Qt signal NavigationToolCollector::Fail() to inform the followers of the latest working status.
void NavigationToolCollector::SetAccuracyRange(double accuracy)
NavigationToolCollector::WorkStatus NavigationToolCollector::GetWorkState() const
Current working state of the collector.
The collector is unique. If the collection task is not completed, the req- uest will fail again. Users are advised to take this factor into account when using. NavigationToolCollector::Pointercollector=NavigationToolCollector::New(); if(collector->GetWorkState()==NavigationToolCollector::Working) { collector->Stop(); } collector->Start();
Referenced by IsRunning, Start.
bool NavigationToolCollector::IsRunning() const
References GetWorkState.
bool NavigationToolCollector::Start(long interval=0)
Start the work of the collector.
Start the work of the collector. It will not stop automatically until the data collection succeeds or fails. At the same time, you can use Stop to stop it. Otherwise, the work of the collector will not stop. interval Filtering frequency of single data frame, in milliseconds. When the parameter is not 0, the Interval property value will be overwritten. Successful startup returns true, otherwise false.
References GetWorkState, SetInterval.
bool NavigationToolCollector::Stop()
Forcibly stop the work of the collector.
void NavigationToolCollector::Fail(int)
The collector encountered an unacceptable error during operation.
Generally speaking, only two conditions trigger this signal. When the input navigation data is determined to be invalid during the acquisition process, the collector will determine that the current nav- igation equipment or environment is unstable, and the operation will be characterized by the conclusion of failure by default. In the acquisition process, if the fluctuation range of the accuracy of the input navigation data is greater than the acceptable range, the co- llector will characterize this operation as a failure. errorCode Enumeration type for the error state of the collector. ErrorCodes
void NavigationToolCollector::Step(int, mitk::NavigationData *)
Operation frame log of collector during operation.
step Current operation frames. data Results of operation frame acquisition.
void NavigationToolCollector::Complete(mitk::NavigationData *)
The collector successfully completes the planned task.
After triggering this signal, the working state of the collector will return to Idea. data Results of operation frame acquisition.
void NavigationToolCollector::on_QtTimerTrigger_timeout()
Referenced by ~NavigationToolCollector.
void NavigationToolCollector::GenerateData() override